package com.tfkz.tfkz2_0.mapper;

import com.tfkz.tfkz2_0.pojo.Product;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    List<Product> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table neuedu_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Product record);
    /*根据商品id查询最新商品*/
    Product selectByIdAndIs_New(@Param("productId") Integer productId, @Param("is_new")Integer is_new);
    /*根据商品id查询最热商品*/
    Product selectByIdAndIs_Hot(@Param("productId") Integer productId, @Param("is_hot")Integer is_hot);
    /*根据商品id查询banner商品*/
    Product selectByIdAndIs_Banner(@Param("productId") Integer productId, @Param("is_banner")Integer is_banner);

    /*根据最新或最热或banner查询商品*/
    List<Product> selectBys_NewAndIs_HotAndIs_Banner(@Param("is_new")Integer is_new,@Param("is_hot")Integer is_hot,@Param("is_banner")Integer is_banner);
}